# Generated by BookLens bootstrap

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(blank=True, default="Unknown", max_length=255)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("reviews_count", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("book_url", models.URLField(unique=True)),
                ("image_url", models.URLField(blank=True, default="")),
                ("summary", models.TextField(blank=True, default="")),
                ("genre", models.CharField(blank=True, default="General", max_length=100)),
                ("sentiment", models.CharField(blank=True, default="Neutral", max_length=100)),
                ("ai_processed", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="BookChunk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chunk_index", models.PositiveIntegerField()),
                ("content", models.TextField()),
                ("token_count", models.PositiveIntegerField(default=0)),
                ("vector_id", models.CharField(max_length=128, unique=True)),
                (
                    "book",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chunks", to="books.book"),
                ),
            ],
            options={"ordering": ["book", "chunk_index"], "unique_together": {("book", "chunk_index")}},
        ),
        migrations.CreateModel(
            name="QAInteraction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("sources", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qa_logs",
                        to="books.book",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
